version: "3"

services:
  web:
    build:
      context: .
      args:
        env: production
        port: 8080
    command: yarn run start
    volumes:
      - ./dist:/app/dist
    ports:
      - "8080:8080"